version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:00'
      timezone: UTC
    open-pull-requests-limit: 10
    groups:
      npm-root-dependencies:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      time: '04:10'
      timezone: UTC
    open-pull-requests-limit: 10
    groups:
      npm-backend-dependencies:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: '04:20'
      timezone: UTC
    open-pull-requests-limit: 10
    groups:
      npm-frontend-dependencies:
        patterns:
          - '*'

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      time: '04:30'
      timezone: UTC

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: '04:40'
      timezone: UTC

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:50'
      timezone: UTC
